# Build using Alire.
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@v2
       - name: Update apt
         if: runner.os == 'Linux'
         run: sudo apt-get update
       - name: Update
         run: alr index --update-all
       - name: Build
         run: alr --non-interactive build
         
  release:
    name: Continuous AppImage
    runs-on: ubuntu-20.04
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: alr2appimage-action
         uses: mgrojo/alr2appimage-action@main
         with:
           alr2appimageVersion: 0.9.3
